#!/usr/bin/env python3
"""Build phase-2 raw seed candidates for data expansion.

This script starts the second-stage data expansion. It intentionally writes to
data/raw only, keeps every row as needs_revision, and does not merge anything
into the processed training set.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "data/raw/phase2_seed_candidates.jsonl"
BATCH = "phase2_v1_context_hard_negative"


def context(
    *,
    title: str,
    topic: str,
    parent: str = "",
    replies: list[str] | None = None,
    description: str = "",
    time: str = "",
) -> dict[str, Any]:
    return {
        "title": title,
        "description": description,
        "parent_comment": parent,
        "reply_chain": replies or [],
        "time": time,
        "topic": topic,
    }


def evidence_strength(risk: str) -> str:
    return {"high": "strong", "medium": "moderate", "low": "weak", "none": "weak"}[risk]


def ambiguity(risk: str) -> str:
    return {"high": "medium", "medium": "medium", "low": "high", "none": "low"}[risk]


def reasoning(case: dict[str, Any]) -> dict[str, Any]:
    risk = case["risk"]
    text = case["text"]
    if risk == "none":
        return {
            "literal_analysis": [f"字面上是在表达：{text}"],
            "encoding_analysis": ["未发现稳定的非字面风险编码；关键词或缩写只作为召回线索。"],
            "context_analysis": [case["context_note"]],
            "supporting_evidence": case.get("support", []),
            "counter_evidence": case["counter"],
            "final_rationale": "普通语境和反证更强，暂标为 none；该条用于训练模型避免关键词误杀。",
        }
    if risk == "low":
        return {
            "literal_analysis": [f"字面上是在表达：{text}"],
            "encoding_analysis": [case["encoding_note"]],
            "context_analysis": [case["context_note"]],
            "supporting_evidence": case["support"],
            "counter_evidence": case["counter"],
            "final_rationale": "存在弱风险信号，但普通解释仍较强，暂标为 low。",
        }
    return {
        "literal_analysis": [f"字面上是在表达：{text}"],
        "encoding_analysis": [case["encoding_note"]],
        "context_analysis": [case["context_note"]],
        "supporting_evidence": case["support"],
        "counter_evidence": case["counter"],
        "final_rationale": f"文本和上下文共同支持风险解释，暂标为 {risk}；仍需人工复核。",
    }


def build_sample(index: int, case: dict[str, Any]) -> dict[str, Any]:
    risk = case["risk"]
    sample_id = f"PHASE2_SEED_{index:04d}_{case['cluster_code']}_{risk.upper()}"
    return {
        "id": sample_id,
        "source_type": "synthetic",
        "platform": case["platform"],
        "text": case["text"],
        "context": case["context"],
        "risk_level": risk,
        "encoding_primary": "none" if risk == "none" else case["primary"],
        "encoding_secondary": case.get("secondary", []),
        "context_required": case.get("context_required", True),
        "ambiguity": case.get("ambiguity", ambiguity(risk)),
        "evidence_strength": case.get("evidence_strength", evidence_strength(risk)),
        "hard_negative": case.get("hard_negative", risk in {"none", "low"}),
        "target_known": case.get("target_known", False),
        "target_reference": case.get("target_reference", "匿名化风险语境"),
        "should_explain_target": False,
        "freshness": "stable",
        "reasoning": reasoning(case),
        "quality_status": "needs_revision",
        "review_notes": (
            f"source=phase2_seed; batch={BATCH}; axis={case['axis']}; "
            f"cluster={case['cluster']}; variant={case['variant']}; not_merged; needs_human_review"
        ),
    }


CASES: list[dict[str, Any]] = [
    {
        "axis": "risk_word_context",
        "cluster": "gambling_hard_negative",
        "cluster_code": "GAMBLE_HN",
        "variant": "anti_gambling_slogan",
        "platform": "抖音",
        "text": "珍爱生活，远离赌博，别把一家人的日子都压上去",
        "context": context(title="反赌公益短片评论区", topic="赌博相关表达", replies=["看完真的后怕", "家里有人吃过亏"]),
        "risk": "none",
        "context_required": True,
        "context_note": "上下文是反赌公益宣传，评论表达劝阻和警示。",
        "counter": ["明确反对赌博，没有招揽、盘口、下注或导流。", "语气是安全教育和家庭劝阻。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "gambling_hard_negative",
        "cluster_code": "GAMBLE_HN",
        "variant": "news_report",
        "platform": "微博",
        "text": "报道里说的赌球链条太吓人了，希望后续能查到底",
        "context": context(title="警方通报网络赌博案件", topic="赌博相关表达", replies=["别转发那些链接", "支持严查"]),
        "risk": "none",
        "context_note": "上下文是新闻通报和公众讨论，不是参与或招揽。",
        "counter": ["文本要求查处风险行为。", "没有提供参与方式或交易信息。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "gambling_contextual",
        "cluster_code": "GAMBLE_CTX",
        "variant": "odds_hint",
        "platform": "贴吧",
        "text": "今晚那场别问，老地方看水位，别在楼里说",
        "context": context(title="比赛前瞻讨论帖", topic="赌博相关表达", parent="有人问怎么买稳一点", replies=["懂了", "别留痕"]),
        "risk": "medium",
        "primary": "E1_平台黑话",
        "secondary": ["C4_典故/物品/符号借用"],
        "context_note": "结合上级评论，水位和老地方更像盘口暗示。",
        "encoding_note": "使用盘口相关黑话和平台规避表达，单看 text 证据不足。",
        "support": ["上级评论提到怎么买稳一点。", "出现老地方、别在楼里说等规避信号。"],
        "counter": ["也可能是普通比赛数据讨论，缺少具体交易或链接。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "gambling_contextual",
        "cluster_code": "GAMBLE_CTX",
        "variant": "normal_sports_data",
        "platform": "虎扑",
        "text": "这场水位变化像是市场太看好主队了",
        "context": context(title="赛事数据复盘", topic="体育讨论", replies=["只看数据不买", "赔率变化确实明显"]),
        "risk": "low",
        "primary": "C4_典故/物品/符号借用",
        "context_note": "语境偏体育数据复盘，存在词汇撞车但未形成参与风险。",
        "encoding_note": "水位可能与盘口语境相关，但也常用于数据讨论。",
        "support": ["出现可能关联盘口的词。"],
        "counter": ["上下文明确是数据复盘。", "没有招揽下注、导流或规避检测。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "fraud_hard_negative",
        "cluster_code": "FRAUD_HN",
        "variant": "anti_fraud_warning",
        "platform": "小红书",
        "text": "刷单返利这种话术真的别信，先让你赚小钱后面就套住",
        "context": context(title="反诈经验分享", topic="诈骗风险词", replies=["我妈差点被骗", "收藏给家人看"]),
        "risk": "none",
        "context_note": "上下文是反诈提醒，解释骗局套路。",
        "counter": ["明确提醒不要相信刷单返利。", "没有招募、付款或联系方式。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "fraud_hard_negative",
        "cluster_code": "FRAUD_HN",
        "variant": "job_safety",
        "platform": "知乎",
        "text": "招聘里写先垫钱刷单的，基本可以直接绕开",
        "context": context(title="应届生求职避坑", topic="求职安全", replies=["正规公司不会这样", "谢谢提醒"]),
        "risk": "none",
        "context_note": "上下文是求职避坑，评论是在识别骗局。",
        "counter": ["文本表达拒绝可疑岗位。", "没有招揽刷单或导流私下交易。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "fraud_contextual",
        "cluster_code": "FRAUD_CTX",
        "variant": "rebate_recruit",
        "platform": "微信群",
        "text": "想空闲赚点的看群公告，垫一单返两单，别外传",
        "context": context(title="兼职信息群", topic="诈骗风险词", replies=["怎么进", "先交多少"]),
        "risk": "high",
        "primary": "C4_典故/物品/符号借用",
        "secondary": ["E1_平台黑话"],
        "context_note": "上下文是兼职群，出现垫单返利和别外传，疑似刷单诈骗招揽。",
        "encoding_note": "用模糊兼职话术包装高风险交易/诈骗场景。",
        "support": ["垫一单返两单是典型可疑返利结构。", "回复链询问进入和付款。"],
        "counter": ["未出现完整支付流程，但风险信号已较强。"],
        "hard_negative": False,
    },
    {
        "axis": "risk_word_context",
        "cluster": "recruitment_hard_negative",
        "cluster_code": "JOB_HN",
        "variant": "formal_recruitment",
        "platform": "小红书",
        "text": "公司官网也有这个岗位，投递入口在招聘页，别加私人号",
        "context": context(title="校招信息分享", topic="正规招聘", replies=["官网查到了", "谢谢提醒别被骗"]),
        "risk": "none",
        "context_note": "上下文是正规招聘信息核验，强调官网投递。",
        "counter": ["明确反对加私人号。", "没有私下收费、垫付或异常导流。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "recruitment_contextual",
        "cluster_code": "JOB_CTX",
        "variant": "private_contact",
        "platform": "QQ群",
        "text": "岗位不方便公开说，先加我，资料费很少，名额快没了",
        "context": context(title="兼职群消息", topic="招聘/诈骗边界", replies=["能不能先看合同", "为什么要先交"]),
        "risk": "medium",
        "primary": "E1_平台黑话",
        "context_note": "上下文是兼职招募，出现不公开、加我、资料费、名额紧张等风险信号。",
        "encoding_note": "用模糊岗位和私下联系规避公开审查。",
        "support": ["出现私下导流和先收费。", "回复链质疑合同和缴费。"],
        "counter": ["缺少明确诈骗结果，仍需人工复核。"],
        "hard_negative": False,
    },
    {
        "axis": "risk_word_context",
        "cluster": "cyber_hard_negative",
        "cluster_code": "CYBER_HN",
        "variant": "defense_article",
        "platform": "知乎",
        "text": "这篇漏洞复盘重点是怎么补，不是教人去打别人站",
        "context": context(title="Web 安全防护复盘", topic="网络安全", replies=["已打码关键细节", "只讲修复方案"]),
        "risk": "none",
        "context_note": "上下文是安全防护文章，强调修复和打码。",
        "counter": ["明确反对攻击他人站点。", "没有给出可执行攻击步骤或目标。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "cyber_contextual",
        "cluster_code": "CYBER_CTX",
        "variant": "exploit_request",
        "platform": "论坛",
        "text": "别讲原理了，能不能给个能直接跑的版本",
        "context": context(title="漏洞防护讨论", topic="网络安全", parent="这里只讨论如何修补", replies=["这就越界了", "别发"]),
        "risk": "medium",
        "primary": "E1_平台黑话",
        "secondary": ["C4_典故/物品/符号借用"],
        "context_note": "上级评论限定防护，文本索要直接可运行版本，偏离安全教育。",
        "encoding_note": "用含糊的版本指代可执行风险内容。",
        "support": ["上下文已提示只讨论修补。", "回复链认为越界。"],
        "counter": ["未出现具体目标或代码内容。"],
        "hard_negative": False,
    },
    {
        "axis": "risk_word_context",
        "cluster": "commerce_hard_negative",
        "cluster_code": "SHOP_HN",
        "variant": "normal_customer_service",
        "platform": "淘宝评论",
        "text": "尺码问题可以私信客服，页面上也有退换规则",
        "context": context(title="鞋子测评评论区", topic="正常电商", replies=["客服回复挺快", "按规则退了"]),
        "risk": "none",
        "context_note": "上下文是普通电商售后，私信客服属于正常流程。",
        "counter": ["没有异常导流、规避平台或私下交易。", "页面有公开退换规则。"],
    },
    {
        "axis": "platform_black_slang",
        "cluster": "homepage_contextual",
        "cluster_code": "HOME_CTX",
        "variant": "portfolio_homepage",
        "platform": "B站",
        "text": "作品集放主页了，想看完整排版可以点进去",
        "context": context(title="设计作业展示", topic="作品分享", replies=["排版很干净", "求字体名"]),
        "risk": "none",
        "context_note": "上下文是作品集分享，主页指向公开作品展示。",
        "counter": ["没有联系方式、交易、低俗或规避表达。", "回复围绕设计内容。"],
    },
    {
        "axis": "platform_black_slang",
        "cluster": "homepage_contextual",
        "cluster_code": "HOME_CTX",
        "variant": "suspicious_homepage",
        "platform": "抖音",
        "text": "这里不方便放，主页第一条自己看，别问太细",
        "context": context(title="同城评论区", topic="平台规避/导流", replies=["又是这种号", "刚才删了一条"]),
        "risk": "medium",
        "primary": "E1_平台黑话",
        "context_note": "上下文是同城评论区且有重复删评提示，主页第一条更像导流规避。",
        "encoding_note": "通过主页第一条和别问太细规避公开表达。",
        "support": ["出现平台导流暗示。", "回复链提示类似账号和删评。"],
        "counter": ["未明确说明导流内容，仍需复核。"],
        "hard_negative": False,
    },
    {
        "axis": "platform_black_slang",
        "cluster": "group_hard_negative",
        "cluster_code": "GROUP_HN",
        "variant": "class_group",
        "platform": "微信群",
        "text": "作业模板发班群了，没收到的找学习委员补一下",
        "context": context(title="课程通知", topic="正常群聊", replies=["收到了", "谢谢"]),
        "risk": "none",
        "context_note": "上下文是课程通知，群用于班级资料共享。",
        "counter": ["没有交易、规避或风险内容。", "回复与学习资料相关。"],
    },
    {
        "axis": "platform_black_slang",
        "cluster": "group_contextual",
        "cluster_code": "GROUP_CTX",
        "variant": "private_group",
        "platform": "贴吧",
        "text": "这边别发关键词，进小群说，图我都备好了",
        "context": context(title="同城闲聊帖", topic="平台规避/导流", replies=["别在吧里留", "私下发"]),
        "risk": "medium",
        "primary": "E1_平台黑话",
        "secondary": ["F_组合编码"],
        "context_note": "文本和回复链都强调避开公开平台，存在私域导流和规避检测。",
        "encoding_note": "关键词、小群、图都备好共同构成规避表达。",
        "support": ["明确要求别发关键词。", "回复链要求私下发。"],
        "counter": ["缺少具体风险对象，不能直接判最高。"],
        "hard_negative": False,
    },
    {
        "axis": "meme_forensics",
        "cluster": "history_course_hard_negative",
        "cluster_code": "HIST_HN",
        "variant": "normal_history_class",
        "platform": "B站",
        "text": "这段讲史料互证挺清楚的，不是所有历史类比都能直接套现实",
        "context": context(title="历史公开课：史料方法", topic="历史课程", replies=["老师一直强调别乱套", "适合期末复习"]),
        "risk": "none",
        "context_note": "上下文是历史方法课程，评论反而提醒不要乱做现实类比。",
        "counter": ["没有现实对象映射。", "文本明确反对机械类比。"],
    },
    {
        "axis": "meme_forensics",
        "cluster": "history_analogy_contextual",
        "cluster_code": "HIST_CTX",
        "variant": "history_repeats",
        "platform": "微博",
        "text": "又是熟悉的剧本，先说为了大家好，后面就不让问了",
        "context": context(title="公共政策争议评论区", topic="历史影射", replies=["历史总是相似", "别展开"]),
        "risk": "medium",
        "primary": "D1_反讽",
        "secondary": ["E3_话题/热点触发"],
        "context_note": "上下文是公共政策争议，回复链提示历史相似和别展开。",
        "encoding_note": "用熟悉的剧本和不让问构成反讽式现实影射。",
        "support": ["与现实争议话题相关。", "回复链强化影射读法。"],
        "counter": ["未指明具体历史事件或对象，存在泛化抱怨可能。"],
        "hard_negative": False,
    },
    {
        "axis": "meme_forensics",
        "cluster": "date_number_hard_negative",
        "cluster_code": "NUM_HN",
        "variant": "normal_product_code",
        "platform": "小红书",
        "text": "这个 64G 版本够用了，主要是照片不要全存在本地",
        "context": context(title="手机容量选择", topic="普通数字", replies=["128G 更安心", "我也觉得"]),
        "risk": "none",
        "context_required": True,
        "context_note": "上下文是手机容量讨论，数字是存储规格。",
        "counter": ["数字与商品容量直接相关。", "没有日期、事件或现实影射线索。"],
    },
    {
        "axis": "meme_forensics",
        "cluster": "date_number_contextual",
        "cluster_code": "NUM_CTX",
        "variant": "ambiguous_date",
        "platform": "B站",
        "text": "五月三十五这天，评论区怎么突然安静了",
        "context": context(title="老视频弹幕回看", topic="数字/日期代指", replies=["别问", "每年都这样"]),
        "risk": "high",
        "primary": "C3_数字代指",
        "secondary": ["E2_时间节点触发"],
        "context_note": "异常日期和每年都这样、别问等回复共同支持日期代指。",
        "encoding_note": "通过不真实日期规避直接日期表达。",
        "support": ["五月三十五是不自然日期。", "回复链表现出共同规避共识。"],
        "counter": ["也可能是梗化表达，但上下文共识较强。"],
        "hard_negative": False,
    },
    {
        "axis": "meme_forensics",
        "cluster": "film_review_hard_negative",
        "cluster_code": "FILM_HN",
        "variant": "normal_character_discussion",
        "platform": "豆瓣",
        "text": "这个角色前期隐忍后期翻盘，编剧铺垫得还算完整",
        "context": context(title="电视剧角色讨论", topic="影视评论", replies=["说的是男二那条线", "演员演得不错"]),
        "risk": "none",
        "context_note": "上下文是电视剧角色和剧情讨论。",
        "counter": ["指向明确为影视角色。", "没有现实人物映射或敏感话题连接。"],
    },
    {
        "axis": "meme_forensics",
        "cluster": "character_analogy_contextual",
        "cluster_code": "CHAR_CTX",
        "variant": "character_mapping",
        "platform": "B站",
        "text": "他这套隐忍多年再出来收拾局面的戏码，怎么越看越眼熟",
        "context": context(title="现实人物纪录片剪辑", topic="人物代指", replies=["别点名", "懂的自然懂"]),
        "risk": "medium",
        "primary": "C1_历史人物类比",
        "secondary": ["D3_借代"],
        "context_note": "标题是现实人物纪录片，回复链提示别点名和共同理解。",
        "encoding_note": "用剧情化人物叙事映射现实人物经历。",
        "support": ["文本强调隐忍多年、出来收拾局面。", "上下文明确现实人物相关。"],
        "counter": ["没有直接目标名称，映射仍需人工确认。"],
        "hard_negative": False,
    },
    {
        "axis": "risk_word_context",
        "cluster": "insult_hard_negative",
        "cluster_code": "ABUSE_HN",
        "variant": "quote_moderation_rule",
        "platform": "知乎",
        "text": "社区规则里这些骂人词只是举例，重点还是别攻击具体用户",
        "context": context(title="社区治理规则讨论", topic="辱骂攻击", replies=["引用规则不算骂人", "关键看指向"]),
        "risk": "none",
        "context_note": "上下文是规则讨论和引用，不是实际攻击。",
        "counter": ["文本强调不要攻击用户。", "没有攻击对象或辱骂意图。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "insult_contextual",
        "cluster_code": "ABUSE_CTX",
        "variant": "coded_group_attack",
        "platform": "微博",
        "text": "那帮人又开始装可怜了，老称呼我就不打出来了",
        "context": context(title="地域争议话题", topic="辱骂攻击", replies=["别带地图炮", "又来了"]),
        "risk": "medium",
        "primary": "E1_平台黑话",
        "secondary": ["D1_反讽"],
        "context_note": "上下文是地域争议，文本指向群体并提示规避旧称呼。",
        "encoding_note": "用不打出来的老称呼回避直接群体攻击词。",
        "support": ["出现那帮人和老称呼。", "回复链提醒地图炮。"],
        "counter": ["没有写出具体辱骂词，仍需上下文复核。"],
        "hard_negative": False,
    },
    {
        "axis": "risk_word_context",
        "cluster": "medical_hard_negative",
        "cluster_code": "MED_HN",
        "variant": "medical_context",
        "platform": "小红书",
        "text": "麻醉药不是止痛糖，术后怎么用一定听医生的",
        "context": context(title="术后护理经验", topic="医学科普", replies=["遵医嘱最重要", "别自己乱吃"]),
        "risk": "none",
        "context_note": "上下文是医学护理和遵医嘱提醒。",
        "counter": ["明确要求听医生指导。", "没有购买、滥用或私下交易。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "legal_hard_negative",
        "cluster_code": "LEGAL_HN",
        "variant": "case_comment",
        "platform": "微博",
        "text": "判决书里提到的违禁品只是案件事实，不代表评论区可以求渠道",
        "context": context(title="法院案例评论区", topic="法律新闻", replies=["别问怎么买", "看案例就行"]),
        "risk": "none",
        "context_note": "上下文是法律案例，文本提醒不要求渠道。",
        "counter": ["明确反对求渠道。", "内容是案件事实讨论。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "illegal_goods_contextual",
        "cluster_code": "GOODS_CTX",
        "variant": "coded_channel",
        "platform": "贴吧",
        "text": "别问名字，老规矩按颜色和批次看，懂货的私下说",
        "context": context(title="同城闲置帖", topic="违禁交易", replies=["别在楼里写", "上次那个还在吗"]),
        "risk": "high",
        "primary": "E1_平台黑话",
        "secondary": ["C4_典故/物品/符号借用"],
        "context_note": "上下文是同城闲置帖，出现老规矩、批次、私下说等交易规避信号。",
        "encoding_note": "通过颜色和批次等替代描述规避直接物品名称。",
        "support": ["明确要求别问名字。", "回复链延续上次那个和别在楼里写。"],
        "counter": ["未出现具体物品名称，但规避和交易语境强。"],
        "hard_negative": False,
    },
    {
        "axis": "platform_black_slang",
        "cluster": "abbreviation_hard_negative",
        "cluster_code": "ABBR_HN",
        "variant": "normal_fandom_abbrev",
        "platform": "微博",
        "text": "这个舞台的 yyds 只是夸现场，别啥缩写都往歪了想",
        "context": context(title="演唱会返图", topic="普通互联网缩写", replies=["饭圈常用语", "确实好看"]),
        "risk": "none",
        "context_note": "上下文是演唱会和饭圈夸奖，缩写为普通网络用语。",
        "counter": ["缩写语义在语境中明确。", "没有规避敏感词或风险指向。"],
    },
    {
        "axis": "platform_black_slang",
        "cluster": "abbreviation_contextual",
        "cluster_code": "ABBR_CTX",
        "variant": "coded_initials",
        "platform": "B站",
        "text": "别打全名了，两个字母就够，大家都知道说的是谁",
        "context": context(title="现实人物争议剪辑", topic="首字母代指", replies=["别冲塔", "缩写保命"]),
        "risk": "medium",
        "primary": "A2_拼音/首字母缩写",
        "secondary": ["E1_平台黑话"],
        "context_note": "上下文是现实人物争议，回复链提示规避和冲塔。",
        "encoding_note": "用首字母替代目标全名以规避平台检测。",
        "support": ["文本明确要求别打全名。", "回复链出现缩写保命。"],
        "counter": ["没有给出具体字母或目标，需人工确认映射。"],
        "hard_negative": False,
    },
    {
        "axis": "risk_word_context",
        "cluster": "violence_hard_negative",
        "cluster_code": "VIOL_HN",
        "variant": "school_safety",
        "platform": "抖音",
        "text": "演练里那些危险动作都是反面教材，现实中千万别模仿",
        "context": context(title="校园安全教育", topic="暴力/安全教育", replies=["学校每年都讲", "安全第一"]),
        "risk": "none",
        "context_note": "上下文是校园安全教育，强调不要模仿。",
        "counter": ["明确反对现实模仿。", "没有煽动或组织行为。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "violence_contextual",
        "cluster_code": "VIOL_CTX",
        "variant": "mobilization_hint",
        "platform": "微信群",
        "text": "光骂没用，今晚谁真敢来现场就知道了",
        "context": context(title="线下冲突传言群", topic="暴力动员", replies=["别闹大", "这话过了"]),
        "risk": "high",
        "primary": "E3_话题/热点触发",
        "secondary": ["D2_夸张/反话"],
        "context_note": "上下文是线下冲突传言，文本具有现实动员意味。",
        "encoding_note": "用真敢来现场表达线下聚集或对抗暗示。",
        "support": ["出现今晚、现场等现实行动线索。", "回复链提醒别闹大。"],
        "counter": ["未说明具体行为，但动员语境强。"],
        "hard_negative": False,
    },
    {
        "axis": "risk_word_context",
        "cluster": "sexual_hard_negative",
        "cluster_code": "SEX_HN",
        "variant": "health_education",
        "platform": "小红书",
        "text": "青春期教育不是低俗内容，家长避而不谈才容易出问题",
        "context": context(title="青少年健康教育讨论", topic="健康教育", replies=["正规科普很重要", "别污名化"]),
        "risk": "none",
        "context_note": "上下文是健康教育和科普正当性讨论。",
        "counter": ["明确是正规教育语境。", "没有低俗招揽或暗示交易。"],
    },
    {
        "axis": "risk_word_context",
        "cluster": "sexual_contextual",
        "cluster_code": "SEX_CTX",
        "variant": "evasive_local",
        "platform": "抖音",
        "text": "同城的别问价，按以前那套说法来，主页有门",
        "context": context(title="同城夜生活评论区", topic="低俗导流", replies=["这个号又来了", "举报了"]),
        "risk": "medium",
        "primary": "E1_平台黑话",
        "secondary": ["C4_典故/物品/符号借用"],
        "context_note": "上下文是同城夜生活评论区，出现别问价、主页有门等导流暗示。",
        "encoding_note": "用旧说法和主页有门规避直接表达。",
        "support": ["出现价格规避和主页导流。", "回复链提示重复可疑账号。"],
        "counter": ["具体服务内容不明，仍需人工复核。"],
        "hard_negative": False,
    },
    {
        "axis": "meme_forensics",
        "cluster": "food_metaphor_hard_negative",
        "cluster_code": "FOOD_HN",
        "variant": "normal_food_review",
        "platform": "大众点评",
        "text": "这家包子皮薄馅多，庆丰路那家反而一般",
        "context": context(title="早餐店测评", topic="普通美食", replies=["我也吃过", "豆浆不错"]),
        "risk": "none",
        "context_note": "上下文是美食测评，地名和食物都有普通解释。",
        "counter": ["评论围绕食物口味。", "没有现实人物、时事或反讽线索。"],
    },
    {
        "axis": "meme_forensics",
        "cluster": "food_metaphor_contextual",
        "cluster_code": "FOOD_CTX",
        "variant": "food_meme",
        "platform": "B站",
        "text": "这包子又被端上来了，评论区还是少蘸点醋吧",
        "context": context(title="时事剪辑评论区", topic="食物/物品隐喻", replies=["别说太明", "又开始了"]),
        "risk": "medium",
        "primary": "C4_典故/物品/符号借用",
        "secondary": ["D1_反讽"],
        "context_note": "上下文是时事剪辑，包子和少蘸醋不再只是美食讨论。",
        "encoding_note": "用食物意象和反讽语气进行隐喻表达。",
        "support": ["标题为时事剪辑。", "回复链提示别说太明。"],
        "counter": ["仍可能是玩笑式食物梗，缺少明确目标。"],
        "hard_negative": False,
    },
]


def hn(
    *,
    axis: str,
    cluster: str,
    code: str,
    variant: str,
    platform: str,
    text: str,
    title: str,
    topic: str,
    replies: list[str],
    note: str,
    counter: list[str],
    parent: str = "",
) -> dict[str, Any]:
    return {
        "axis": axis,
        "cluster": cluster,
        "cluster_code": code,
        "variant": variant,
        "platform": platform,
        "text": text,
        "context": context(title=title, topic=topic, parent=parent, replies=replies),
        "risk": "none",
        "context_note": note,
        "counter": counter,
    }


def risky(
    *,
    axis: str,
    cluster: str,
    code: str,
    variant: str,
    platform: str,
    text: str,
    title: str,
    topic: str,
    risk: str,
    primary: str,
    note: str,
    encoding: str,
    support: list[str],
    counter: list[str],
    replies: list[str],
    parent: str = "",
    secondary: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "axis": axis,
        "cluster": cluster,
        "cluster_code": code,
        "variant": variant,
        "platform": platform,
        "text": text,
        "context": context(title=title, topic=topic, parent=parent, replies=replies),
        "risk": risk,
        "primary": primary,
        "secondary": secondary or [],
        "context_note": note,
        "encoding_note": encoding,
        "support": support,
        "counter": counter,
        "hard_negative": False,
    }


ADDITIONAL_CASES: list[dict[str, Any]] = [
    hn(
        axis="risk_word_context",
        cluster="lottery_hard_negative",
        code="LOTTERY_HN",
        variant="statistics_class",
        platform="B站",
        text="老师拿彩票举例只是讲概率，重点是别把小概率当稳定收益",
        title="概率论入门课",
        topic="赌博/概率边界",
        replies=["这个例子很直观", "期望值那里讲明白了"],
        note="上下文是概率课程，彩票只是教学例子。",
        counter=["文本强调小概率不能当收益。", "没有购买、追号、盘口或导流。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="lottery_contextual",
        code="LOTTERY_CTX",
        variant="coded_lottery_group",
        platform="微信群",
        text="今晚号码别在群名片写，按昨天那套发暗号就行",
        title="彩票交流群",
        topic="赌博/彩票边界",
        risk="medium",
        primary="E1_平台黑话",
        secondary=["C3_数字代指"],
        note="上下文是彩票交流群，文本要求用暗号发布号码。",
        encoding="用暗号和规避公开字段的方式隐藏号码交流。",
        support=["出现号码、暗号和别在群名片写。", "上下文不是概率讨论而是交流群。"],
        counter=["未出现付款或组织下注流程。"],
        replies=["别被封", "老规矩"],
    ),
    hn(
        axis="risk_word_context",
        cluster="card_game_hard_negative",
        code="CARD_HN",
        variant="family_game",
        platform="抖音",
        text="过年家里打牌图个热闹，别带钱就行",
        title="春节家庭 vlog",
        topic="娱乐/赌博边界",
        replies=["纯娱乐可以", "老人开心就好"],
        note="上下文是家庭娱乐，文本明确不带钱。",
        counter=["明确排除金钱输赢。", "没有组织赌局或抽成。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="card_game_contextual",
        code="CARD_CTX",
        variant="private_table",
        platform="QQ群",
        text="桌子差两个人，进来先看规矩，别在外面问底分",
        title="本地牌友群",
        topic="娱乐/赌博边界",
        risk="medium",
        primary="E1_平台黑话",
        note="上下文是本地牌友群，底分和别在外面问提示金钱赌局可能。",
        encoding="用桌子、底分、规矩等圈内词降低直接性。",
        support=["出现底分等赌局信号。", "要求不要在外面问。"],
        counter=["也可能是普通牌局约人，缺少明确金额。"],
        replies=["现在多少水", "私我位置"],
    ),
    hn(
        axis="risk_word_context",
        cluster="loan_hard_negative",
        code="LOAN_HN",
        variant="bank_loan_explainer",
        platform="知乎",
        text="正规贷款先看年化利率和合同，别被低息广告带着走",
        title="消费贷避坑指南",
        topic="金融/诈骗边界",
        replies=["年化和月息差很多", "合同要看清"],
        note="上下文是金融科普和避坑，不是放贷招揽。",
        counter=["强调正规合同和风险提示。", "没有私下放款或收费。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="loan_contextual",
        code="LOAN_CTX",
        variant="private_fast_loan",
        platform="微信群",
        text="急用的私我，不看征信，当天到，手续费先走一下",
        title="同城互助群",
        topic="金融/诈骗边界",
        risk="high",
        primary="C4_典故/物品/符号借用",
        secondary=["E1_平台黑话"],
        note="上下文是同城群，文本含私下放款和先收手续费。",
        encoding="用互助和急用包装高风险金融招揽。",
        support=["不看征信、当天到和先手续费构成强风险。", "通过私我导流。"],
        counter=["未展示真实合同，但风险信号集中。"],
        replies=["要先转多少", "靠谱吗"],
    ),
    hn(
        axis="risk_word_context",
        cluster="stock_hard_negative",
        code="STOCK_HN",
        variant="investment_risk_warning",
        platform="雪球",
        text="群里喊稳赚的都要警惕，投资没有保本神话",
        title="新手投资风险讨论",
        topic="金融/荐股边界",
        replies=["别信老师带单", "先学风险"],
        note="上下文是投资风险教育，文本反对稳赚话术。",
        counter=["明确提醒不要相信保本。", "没有带单或收费群导流。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="stock_contextual",
        code="STOCK_CTX",
        variant="paid_signal_group",
        platform="微博",
        text="明天的票不公开说，进内圈看提示，晚了就没位置",
        title="短线交流评论区",
        topic="金融/荐股边界",
        risk="medium",
        primary="E1_平台黑话",
        note="上下文是短线交流，内圈、提示、没位置带有荐股导流味道。",
        encoding="用票、内圈、位置等模糊词规避直接荐股。",
        support=["出现进内圈和不公开说。", "标题是短线交流。"],
        counter=["未明确收费或承诺收益，需复核。"],
        replies=["怎么进", "老师准吗"],
    ),
    hn(
        axis="risk_word_context",
        cluster="refund_hard_negative",
        code="REFUND_HN",
        variant="consumer_rights",
        platform="小红书",
        text="维权可以走平台客服和消协，别点陌生人发的退款链接",
        title="网购售后避坑",
        topic="退款/诈骗边界",
        replies=["退款链接真的很多坑", "走平台最稳"],
        note="上下文是消费者维权提醒。",
        counter=["明确要求走平台正规渠道。", "没有诱导点击外部链接。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="refund_contextual",
        code="REFUND_CTX",
        variant="fake_refund_link",
        platform="短信截图评论",
        text="订单异常点这个补偿入口，别走平台，平台太慢",
        title="疑似客服私信",
        topic="退款/诈骗边界",
        risk="high",
        primary="E1_平台黑话",
        note="上下文是疑似客服私信，文本引导绕开平台。",
        encoding="以补偿入口包装外部链接导流。",
        support=["要求别走平台。", "以订单异常和补偿制造紧迫感。"],
        counter=["未显示链接内容，但诈骗模式明显。"],
        replies=["这像钓鱼", "别点"],
    ),
    hn(
        axis="platform_black_slang",
        cluster="private_message_hard_negative",
        code="PM_HN",
        variant="after_sale_private",
        platform="淘宝评论",
        text="订单号别发评论区，私信客服处理更安全",
        title="售后问题评论区",
        topic="私信/导流边界",
        replies=["保护隐私", "客服已经处理"],
        note="上下文是售后隐私保护，私信客服是合理流程。",
        counter=["不涉及私下交易。", "原因是避免公开订单号。"],
    ),
    risky(
        axis="platform_black_slang",
        cluster="private_message_contextual",
        code="PM_CTX",
        variant="avoid_platform",
        platform="小红书",
        text="别在评论区问价，平台看得严，私我按老价走",
        title="同城服务评论区",
        topic="私信/导流边界",
        risk="medium",
        primary="E1_平台黑话",
        note="上下文是同城服务，问价、平台严、私我共同形成规避导流。",
        encoding="通过私信绕开平台公开审查。",
        support=["明确提到平台看得严。", "涉及价格和私下沟通。"],
        counter=["服务内容不明，需人工复核。"],
        replies=["你又来了", "别留联系方式"],
    ),
    hn(
        axis="platform_black_slang",
        cluster="cant_say_hard_negative",
        code="CANTSAY_HN",
        variant="spoiler_avoidance",
        platform="B站",
        text="结局不能说，怕剧透，还没看的赶紧去补",
        title="新番完结讨论",
        topic="不能说/规避边界",
        replies=["别剧透", "今晚补完"],
        note="上下文是影视剧透回避，不是平台风险规避。",
        counter=["不能说的原因是避免剧透。", "没有敏感对象或导流。"],
    ),
    risky(
        axis="platform_black_slang",
        cluster="cant_say_contextual",
        code="CANTSAY_CTX",
        variant="risk_evasion",
        platform="微博",
        text="那个名字不能说，说了号就没了，反正大家都知道",
        title="现实争议话题评论区",
        topic="不能说/规避边界",
        risk="medium",
        primary="E1_平台黑话",
        secondary=["A2_拼音/首字母缩写"],
        note="上下文是现实争议话题，文本显式说明说出名称会导致账号风险。",
        encoding="用不能说和大家都知道代替直接命名。",
        support=["出现号就没了的规避检测理由。", "标题涉及现实争议。"],
        counter=["未出现具体目标，映射需复核。"],
        replies=["缩写吧", "别冲"],
    ),
    hn(
        axis="platform_black_slang",
        cluster="emoji_hard_negative",
        code="EMOJI_HN",
        variant="normal_weather_emoji",
        platform="微博",
        text="今天太阳太猛了，🌞🌞🌞出门记得防晒",
        title="天气吐槽",
        topic="表情符号边界",
        replies=["真的晒", "伞救命"],
        note="上下文是天气讨论，emoji 表示太阳。",
        counter=["表情与天气字面一致。", "没有替代敏感词或群体共识。"],
    ),
    risky(
        axis="platform_black_slang",
        cluster="emoji_contextual",
        code="EMOJI_CTX",
        variant="emoji_substitute",
        platform="贴吧",
        text="那个词别打了，用三个🌂代一下就行",
        title="敏感话题边缘讨论",
        topic="表情符号边界",
        risk="medium",
        primary="B4_符号/空格/Unicode 干扰",
        secondary=["E1_平台黑话"],
        note="上下文是敏感话题边缘讨论，文本要求用 emoji 替代某词。",
        encoding="用符号替代直接词面以规避检测。",
        support=["明确说别打那个词。", "要求用 emoji 代替。"],
        counter=["未说明被替代词是什么，需人工复核。"],
        replies=["懂", "别明说"],
    ),
    hn(
        axis="meme_forensics",
        cluster="historical_name_hard_negative",
        code="HNAME_HN",
        variant="normal_biography",
        platform="B站",
        text="这一段讲他早年经历挺细，和后来的选择能对上",
        title="历史人物传记解读",
        topic="历史人物类比边界",
        replies=["史料出处在哪", "讲得很客观"],
        note="上下文是历史人物传记，没有现实映射。",
        counter=["评论关注史料和人物生平。", "没有现实话题或暗示回复链。"],
    ),
    risky(
        axis="meme_forensics",
        cluster="historical_name_contextual",
        code="HNAME_CTX",
        variant="biography_mapping",
        platform="B站",
        text="看似讲古人，其实每句都在照现在这位身上量",
        title="现实人物混剪评论区",
        topic="历史人物类比边界",
        risk="medium",
        primary="C1_历史人物类比",
        secondary=["D3_借代"],
        note="上下文是现实人物混剪，文本明确提示古今映射。",
        encoding="用古人作为现实人物的类比外壳。",
        support=["文本直接说照现在这位身上量。", "标题是现实人物混剪。"],
        counter=["未说明具体古人和现实对象的映射细节。"],
        replies=["别点破", "这个剪法太明显"],
    ),
    hn(
        axis="meme_forensics",
        cluster="anniversary_hard_negative",
        code="ANNIV_HN",
        variant="wedding_anniversary",
        platform="小红书",
        text="今天是我们结婚十周年，翻旧照片真的很感慨",
        title="周年纪念日",
        topic="时间节点边界",
        replies=["祝福", "照片好温柔"],
        note="上下文是个人纪念日，时间节点为私人生活事件。",
        counter=["祝福回复支持生活语境。", "没有公共事件或敏感日期线索。"],
    ),
    risky(
        axis="meme_forensics",
        cluster="anniversary_contextual",
        code="ANNIV_CTX",
        variant="public_memory_hint",
        platform="微博",
        text="又到这天了，大家都只发旧照片，话反而不用说出口",
        title="历史影像转发评论区",
        topic="时间节点边界",
        risk="medium",
        primary="E2_时间节点触发",
        secondary=["C2_历史事件影射"],
        note="上下文是历史影像转发，文本提到这天和不用说出口。",
        encoding="通过时间节点和旧照片形成隐性纪念。",
        support=["出现又到这天和不用说出口。", "标题为历史影像转发。"],
        counter=["没有具体日期和事件名称，证据依赖上下文。"],
        replies=["懂的都懂", "别写全"],
    ),
    hn(
        axis="meme_forensics",
        cluster="animal_metaphor_hard_negative",
        code="ANIMAL_HN",
        variant="pet_story",
        platform="抖音",
        text="这只猫真的会开抽屉，偷零食还装无辜",
        title="宠物日常",
        topic="动物隐喻边界",
        replies=["太聪明了", "猫猫无罪"],
        note="上下文是宠物日常，动物描述为字面含义。",
        counter=["标题和回复都围绕宠物。", "没有现实对象映射。"],
    ),
    risky(
        axis="meme_forensics",
        cluster="animal_metaphor_contextual",
        code="ANIMAL_CTX",
        variant="coded_animal",
        platform="微博",
        text="这只大猫又出来巡视了，下面的小猫都不敢叫",
        title="现实组织会议剪辑",
        topic="动物隐喻边界",
        risk="medium",
        primary="D3_借代",
        secondary=["C4_典故/物品/符号借用"],
        note="上下文是现实组织会议，动物意象可能借代层级关系。",
        encoding="用大猫小猫替代现实人物或组织层级。",
        support=["标题涉及现实组织会议。", "评论呈现上级巡视和下级不敢发声。"],
        counter=["动物比喻本身泛化，目标不够明确。"],
        replies=["别说动物名", "懂了"],
    ),
    hn(
        axis="meme_forensics",
        cluster="vehicle_metaphor_hard_negative",
        code="VEHICLE_HN",
        variant="driving_lesson",
        platform="B站",
        text="下坡别空挡滑行，刹车热衰减真的危险",
        title="新手驾驶安全课",
        topic="车辆隐喻边界",
        replies=["驾校也这么讲", "安全第一"],
        note="上下文是驾驶安全，刹车是字面交通含义。",
        counter=["标题和回复明确为驾驶教学。", "没有现实影射或平台黑话。"],
    ),
    risky(
        axis="meme_forensics",
        cluster="vehicle_metaphor_contextual",
        code="VEHICLE_CTX",
        variant="acceleration_meme",
        platform="B站",
        text="别踩刹车了，这车就是要一路加到底",
        title="公共议题激烈讨论区",
        topic="车辆隐喻边界",
        risk="medium",
        primary="D2_夸张/反话",
        secondary=["C4_典故/物品/符号借用"],
        note="上下文是公共议题争论，车辆动作更像态度隐喻。",
        encoding="用加速和刹车表达对现实议题走向的隐喻态度。",
        support=["标题不是驾驶话题。", "文本使用一路加到底的夸张表达。"],
        counter=["仍可能是泛化比喻，缺少明确目标对象。"],
        replies=["这话别太直", "加速是吧"],
    ),
    hn(
        axis="meme_forensics",
        cluster="book_quote_hard_negative",
        code="BOOK_HN",
        variant="literature_quote",
        platform="豆瓣",
        text="这句台词放在小说里很有宿命感，不必强行联系现实",
        title="小说读书笔记",
        topic="文学引用边界",
        replies=["同意，文本内就能解释", "别过度解读"],
        note="上下文是文学读书笔记，且反对强行现实化。",
        counter=["评论明确不联系现实。", "讨论停留在文本内部。"],
    ),
    risky(
        axis="meme_forensics",
        cluster="book_quote_contextual",
        code="BOOK_CTX",
        variant="quote_mapping",
        platform="微博",
        text="这句书里的话今天看特别合适，谁在装睡大家都清楚",
        title="热点事件评论区",
        topic="文学引用边界",
        risk="medium",
        primary="D3_借代",
        secondary=["E3_话题/热点触发"],
        note="上下文是热点事件，文学引用被用于现实评论。",
        encoding="借书中句子表达对现实对象的评价。",
        support=["出现今天看特别合适。", "热点事件语境支撑现实映射。"],
        counter=["没有引用原句和具体对象，存在泛化批评可能。"],
        replies=["别点名", "这句太贴了"],
    ),
    hn(
        axis="risk_word_context",
        cluster="weapon_news_hard_negative",
        code="WEAPON_HN",
        variant="museum_exhibit",
        platform="B站",
        text="博物馆展柜里这些都是历史展品，别拿现代用途乱联想",
        title="军事博物馆参观记录",
        topic="武器/历史展品边界",
        replies=["讲解员说得很清楚", "历史教育"],
        note="上下文是博物馆历史展品介绍。",
        counter=["明确是展柜和历史教育。", "没有制作、购买或使用意图。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="weapon_contextual",
        code="WEAPON_CTX",
        variant="parts_hint",
        platform="论坛",
        text="零件别写全名，按图里的编号找，懂装的人自然懂",
        title="同城零件交流帖",
        topic="武器/违禁边界",
        risk="high",
        primary="E1_平台黑话",
        secondary=["B4_符号/空格/Unicode 干扰"],
        note="上下文是同城零件交流，文本要求用编号替代全名。",
        encoding="用编号和懂装的人规避直接物品名称。",
        support=["明确要求别写全名。", "出现懂装的人和同城交流。"],
        counter=["具体零件类别未明，但规避和装配语境强。"],
        replies=["别发细节", "私下说"],
    ),
    hn(
        axis="risk_word_context",
        cluster="explosive_science_hard_negative",
        code="EXP_HN",
        variant="chemistry_safety",
        platform="知乎",
        text="化学课讲反应危险性，是为了知道怎么避免事故",
        title="实验室安全规范",
        topic="化学安全边界",
        replies=["护目镜真的要戴", "老师反复强调"],
        note="上下文是实验室安全教育。",
        counter=["目的为避免事故。", "没有配方、获取或实施指导。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="explosive_contextual",
        code="EXP_CTX",
        variant="recipe_request",
        platform="贴吧",
        text="别再科普安全了，我就想知道比例怎么配才响",
        title="化学实验讨论帖",
        topic="化学安全边界",
        risk="high",
        primary="C4_典故/物品/符号借用",
        note="上下文是化学实验帖，文本明确索要危险比例。",
        encoding="用才响等口语化说法指向危险制备效果。",
        support=["直接索要比例。", "拒绝安全科普。"],
        counter=["没有列出具体材料，但意图信号强。"],
        replies=["这不能发", "举报了"],
    ),
    hn(
        axis="risk_word_context",
        cluster="drug_medical_hard_negative",
        code="DRUG_HN",
        variant="prescription_warning",
        platform="小红书",
        text="处方药别互相推荐，症状像也不代表能吃同一种",
        title="用药安全提醒",
        topic="药物/违禁边界",
        replies=["遵医嘱", "别乱吃"],
        note="上下文是用药安全提醒。",
        counter=["明确反对互相推荐药物。", "没有购买渠道或滥用暗示。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="drug_contextual",
        code="DRUG_CTX",
        variant="coded_supply",
        platform="微信群",
        text="名字别打，按小白片问就行，剩的不多了",
        title="病友闲聊群",
        topic="药物/违禁边界",
        risk="medium",
        primary="C4_典故/物品/符号借用",
        secondary=["E1_平台黑话"],
        note="上下文是病友群，但文本出现别打名字和剩余数量，疑似私下供给。",
        encoding="用小白片替代具体药名并规避公开表达。",
        support=["要求名字别打。", "出现剩的不多了的供给信号。"],
        counter=["也可能是普通处方药讨论，缺少交易细节。"],
        replies=["能寄吗", "别在群里说"],
    ),
    hn(
        axis="risk_word_context",
        cluster="adult_content_hard_negative",
        code="ADULT_HN",
        variant="film_rating",
        platform="豆瓣",
        text="分级讨论不是低俗，关键是保护未成年人观看边界",
        title="电影分级制度讨论",
        topic="低俗/分级边界",
        replies=["应该科普", "别一刀切"],
        note="上下文是电影分级制度讨论。",
        counter=["文本关注保护边界。", "没有低俗导流或暗示交易。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="adult_content_contextual",
        code="ADULT_CTX",
        variant="preview_evasion",
        platform="抖音",
        text="预览不能放太多，想看完整版按评论区暗号找",
        title="擦边剪辑评论区",
        topic="低俗/导流边界",
        risk="medium",
        primary="E1_平台黑话",
        secondary=["B4_符号/空格/Unicode 干扰"],
        note="上下文是擦边剪辑，文本导向暗号查找完整版。",
        encoding="用预览、完整版、暗号规避平台限制。",
        support=["出现暗号和完整版导流。", "标题为擦边剪辑评论区。"],
        counter=["未直接出现交易或具体内容，需复核。"],
        replies=["又骗主页流量", "别上当"],
    ),
    hn(
        axis="risk_word_context",
        cluster="abuse_quote_hard_negative",
        code="QUOTE_HN",
        variant="screenshot_discussion",
        platform="微博",
        text="截图里的脏话打码是对的，讨论事情别复读那些词",
        title="网暴事件复盘",
        topic="辱骂/引用边界",
        replies=["打码挺好", "别二次伤害"],
        note="上下文是网暴复盘和反二次伤害。",
        counter=["文本反对复读辱骂。", "没有攻击新对象。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="abuse_contextual",
        code="ABUSE2_CTX",
        variant="nickname_attack",
        platform="贴吧",
        text="那群人老外号我就不写了，反正一看口音就知道",
        title="地域争议帖",
        topic="辱骂/群体攻击边界",
        risk="medium",
        primary="E1_平台黑话",
        secondary=["D3_借代"],
        note="上下文是地域争议，文本用老外号和口音暗示群体攻击。",
        encoding="规避写出群体辱称，但保留指向。",
        support=["出现那群人、老外号和口音。", "标题为地域争议。"],
        counter=["未写出具体辱称，需结合上下文复核。"],
        replies=["别地图炮", "这话不合适"],
    ),
    hn(
        axis="risk_word_context",
        cluster="public_affairs_hard_negative",
        code="PUBLIC_HN",
        variant="policy_explainer",
        platform="知乎",
        text="政策解读先看原文，别只截一句话带节奏",
        title="公共政策问答",
        topic="公共事务边界",
        replies=["全文链接在这", "断章取义不行"],
        note="上下文是政策解读和信息核验。",
        counter=["鼓励看原文和避免带节奏。", "没有隐晦攻击或动员。"],
    ),
    risky(
        axis="meme_forensics",
        cluster="public_affairs_contextual",
        code="PUBLIC_CTX",
        variant="policy_sarcasm",
        platform="微博",
        text="先说都是为你好，再让你别问为什么，这流程太熟了",
        title="公共政策争议评论区",
        topic="公共事务边界",
        risk="medium",
        primary="D1_反讽",
        secondary=["E3_话题/热点触发"],
        note="上下文是公共政策争议，文本通过流程化描述表达反讽。",
        encoding="用为你好和别问为什么构造隐性批评。",
        support=["话题为公共政策争议。", "文本带明显反讽结构。"],
        counter=["没有具体对象，可能是泛化不满。"],
        replies=["这话太熟", "别展开"],
    ),
    hn(
        axis="meme_forensics",
        cluster="place_name_hard_negative",
        code="PLACE_HN",
        variant="travel_note",
        platform="小红书",
        text="广场晚上灯光很好看，带三脚架拍夜景很稳",
        title="城市旅行攻略",
        topic="地名/地点边界",
        replies=["夜景好看", "注意保管设备"],
        note="上下文是旅行摄影，地点为字面旅游场景。",
        counter=["回复围绕夜景和摄影。", "没有事件影射或纪念语境。"],
    ),
    risky(
        axis="meme_forensics",
        cluster="place_name_contextual",
        code="PLACE_CTX",
        variant="square_hint",
        platform="微博",
        text="今晚别写地名，发个空广场照片就够了",
        title="历史照片转发",
        topic="地名/地点边界",
        risk="medium",
        primary="C4_典故/物品/符号借用",
        secondary=["E2_时间节点触发"],
        note="上下文是历史照片转发，文本要求用空广场照片替代地名。",
        encoding="用地点图像代替直接地点名称。",
        support=["明确说别写地名。", "历史照片语境增强影射。"],
        counter=["缺少具体时间和地点，仍需复核。"],
        replies=["懂了", "别写全"],
    ),
    hn(
        axis="platform_black_slang",
        cluster="unicode_hard_negative",
        code="UNICODE_HN",
        variant="aesthetic_spacing",
        platform="小红书",
        text="标题加空格只是为了排版，不是所有空格都是规避",
        title="笔记排版技巧",
        topic="符号空格边界",
        replies=["排版确实舒服", "封面也重要"],
        note="上下文是排版技巧，空格有普通设计目的。",
        counter=["文本明确说明排版目的。", "没有敏感词拆分或规避语境。"],
    ),
    risky(
        axis="platform_black_slang",
        cluster="unicode_contextual",
        code="UNICODE_CTX",
        variant="split_keyword",
        platform="微博",
        text="中间加点空格就能过，别连着打那几个字",
        title="平台审核吐槽区",
        topic="符号空格边界",
        risk="medium",
        primary="B4_符号/空格/Unicode 干扰",
        secondary=["E1_平台黑话"],
        note="上下文是平台审核吐槽，文本提供拆分关键词规避方式。",
        encoding="通过空格打断关键词以规避检测。",
        support=["明确说加空格就能过。", "要求别连着打那几个字。"],
        counter=["未说明具体词，风险等级不宜直接最高。"],
        replies=["别教", "会被删"],
    ),
    hn(
        axis="platform_black_slang",
        cluster="initials_hard_negative",
        code="INIT_HN",
        variant="normal_tech_initials",
        platform="知乎",
        text="CPU 和 GPU 这些缩写是硬件名，别按拼音首字母乱猜",
        title="电脑配置入门",
        topic="首字母缩写边界",
        replies=["小白友好", "显卡那里讲清楚了"],
        note="上下文是硬件科普，缩写是技术术语。",
        counter=["缩写含义在上下文中明确。", "没有代指现实对象。"],
    ),
    risky(
        axis="platform_black_slang",
        cluster="initials_contextual",
        code="INIT_CTX",
        variant="initials_target",
        platform="B站",
        text="全名别打，三个首字母够了，评论区都懂",
        title="现实人物争议剪辑",
        topic="首字母缩写边界",
        risk="medium",
        primary="A2_拼音/首字母缩写",
        secondary=["E1_平台黑话"],
        note="上下文是现实人物争议，文本要求用首字母替代全名。",
        encoding="用拼音首字母进行目标规避。",
        support=["明确要求全名别打。", "评论区都懂表明群体共识。"],
        counter=["没有给出首字母内容，仍需复核。"],
        replies=["缩写保命", "别冲塔"],
    ),
    hn(
        axis="meme_forensics",
        cluster="color_hard_negative",
        code="COLOR_HN",
        variant="design_color",
        platform="小红书",
        text="这个红配黄有点复古，像老海报的配色",
        title="海报设计点评",
        topic="颜色符号边界",
        replies=["复古感有了", "字体也搭"],
        note="上下文是设计点评，颜色是视觉风格。",
        counter=["评论围绕设计元素。", "没有组织、旗帜或现实隐喻。"],
    ),
    risky(
        axis="meme_forensics",
        cluster="color_contextual",
        code="COLOR_CTX",
        variant="symbolic_color",
        platform="微博",
        text="今天大家都只发这个颜色，不说话也够明显了",
        title="热点事件纪念日",
        topic="颜色符号边界",
        risk="medium",
        primary="C4_典故/物品/符号借用",
        secondary=["E2_时间节点触发"],
        note="上下文是热点事件纪念日，颜色可能成为共同符号。",
        encoding="用颜色替代直接表态或纪念文本。",
        support=["出现今天大家都只发这个颜色。", "标题为纪念日语境。"],
        counter=["颜色具体含义未说明，依赖上下文。"],
        replies=["懂", "别写字"],
    ),
    hn(
        axis="risk_word_context",
        cluster="charity_hard_negative",
        code="CHARITY_HN",
        variant="official_donation",
        platform="微博",
        text="捐款请走官方公示渠道，评论区私人二维码都别扫",
        title="灾后救助信息汇总",
        topic="公益/诈骗边界",
        replies=["官方链接在置顶", "谨防冒充"],
        note="上下文是公益捐助防骗提醒。",
        counter=["明确反对私人二维码。", "引导官方渠道。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="charity_contextual",
        code="CHARITY_CTX",
        variant="private_qr",
        platform="微信群",
        text="官方太慢，先扫我这个码，名单后面统一补",
        title="灾后互助群",
        topic="公益/诈骗边界",
        risk="medium",
        primary="E1_平台黑话",
        note="上下文是灾后互助群，文本引导绕开官方捐助渠道。",
        encoding="用互助和补名单包装私人收款。",
        support=["要求先扫私人码。", "以官方太慢为理由绕开正规渠道。"],
        counter=["可能是临时互助，但缺少公开核验。"],
        replies=["有公示吗", "别乱扫"],
    ),
    hn(
        axis="risk_word_context",
        cluster="account_trade_hard_negative",
        code="ACCOUNT_HN",
        variant="account_security",
        platform="知乎",
        text="账号被盗先改密码和申诉，别在评论区找所谓找回团队",
        title="账号安全指南",
        topic="账号交易/黑产边界",
        replies=["官方申诉最靠谱", "别给验证码"],
        note="上下文是账号安全指南。",
        counter=["文本提醒走官方申诉。", "没有买卖账号或黑产导流。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="account_trade_contextual",
        code="ACCOUNT_CTX",
        variant="recovery_team",
        platform="贴吧",
        text="号没了别急，老团队还能捞，资料别发楼里",
        title="账号申诉失败求助帖",
        topic="账号交易/黑产边界",
        risk="medium",
        primary="E1_平台黑话",
        secondary=["C4_典故/物品/符号借用"],
        note="上下文是账号申诉，老团队还能捞和别发楼里疑似黑产服务。",
        encoding="用捞号和老团队替代直接黑产服务描述。",
        support=["出现老团队和资料别发楼里。", "回复环境是账号找回求助。"],
        counter=["也可能是普通申诉经验，缺少交易细节。"],
        replies=["多少钱", "私你了"],
    ),
    hn(
        axis="risk_word_context",
        cluster="privacy_hard_negative",
        code="PRIVACY_HN",
        variant="privacy_protection",
        platform="小红书",
        text="晒聊天记录记得把手机号和地址打码，保护一下别人隐私",
        title="吐槽帖发布提醒",
        topic="隐私/人肉边界",
        replies=["打码很重要", "别挂素人"],
        note="上下文是隐私保护提醒。",
        counter=["明确要求打码。", "没有号召搜索或曝光个人信息。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="privacy_contextual",
        code="PRIVACY_CTX",
        variant="doxxing_hint",
        platform="微博",
        text="不用挂全名，学校和班级一放，认识的自然知道",
        title="校园纠纷爆料",
        topic="隐私/人肉边界",
        risk="medium",
        primary="D3_借代",
        secondary=["E1_平台黑话"],
        note="上下文是校园纠纷爆料，学校班级足以形成现实识别。",
        encoding="用间接身份信息替代全名曝光。",
        support=["明确说不用挂全名。", "学校和班级可识别个人。"],
        counter=["未出现完整姓名和联系方式，但隐私风险明显。"],
        replies=["别开盒", "这也能认出来"],
    ),
    hn(
        axis="risk_word_context",
        cluster="rumor_hard_negative",
        code="RUMOR_HN",
        variant="debunking",
        platform="微博",
        text="这张图去年就被辟谣了，别再拿来当新消息传",
        title="谣言核查",
        topic="谣言/煽动边界",
        replies=["原帖链接在这", "已举报造谣"],
        note="上下文是辟谣和事实核查。",
        counter=["文本反对传播假消息。", "提供核查语境。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="rumor_contextual",
        code="RUMOR_CTX",
        variant="panic_forward",
        platform="微信群",
        text="真假先别管，赶紧转给家里人，晚了就来不及",
        title="突发事件群聊",
        topic="谣言/煽动边界",
        risk="medium",
        primary="E3_话题/热点触发",
        note="上下文是突发事件群聊，文本鼓励未经核实的恐慌式转发。",
        encoding="用紧迫感压过事实核查。",
        support=["真假先别管。", "赶紧转和来不及制造恐慌。"],
        counter=["未指明具体谣言内容，风险需结合原消息。"],
        replies=["有来源吗", "别传谣"],
    ),
    hn(
        axis="meme_forensics",
        cluster="homophone_hard_negative",
        code="HOMO_HN",
        variant="typo_joke",
        platform="B站",
        text="输入法又把同学打成铜学了，弹幕别笑太大声",
        title="课堂切片",
        topic="谐音/错字边界",
        replies=["输入法背锅", "纯错字"],
        note="上下文是输入法错字和普通玩笑。",
        counter=["文本主动解释为输入法错误。", "没有目标代指或风险语境。"],
    ),
    risky(
        axis="platform_black_slang",
        cluster="homophone_contextual",
        code="HOMO_CTX",
        variant="intentional_homophone",
        platform="微博",
        text="别写原词，用这个谐音，读出来就知道骂谁",
        title="争议人物评论区",
        topic="谐音/错字边界",
        risk="medium",
        primary="A1_普通谐音",
        secondary=["E1_平台黑话"],
        note="上下文是争议人物评论区，文本明确要求用谐音规避原词。",
        encoding="通过读音相近替代直接攻击词或目标词。",
        support=["明确说别写原词。", "读出来就知道骂谁说明存在目标映射。"],
        counter=["未给出具体谐音词，需人工确认。"],
        replies=["别太明显", "会被搜到"],
    ),
    hn(
        axis="risk_word_context",
        cluster="school_chat_hard_negative",
        code="SCHOOL_HN",
        variant="exam_group",
        platform="QQ群",
        text="答案解析等老师发，别在群里传来路不明的所谓押题",
        title="班级备考群",
        topic="考试/诈骗边界",
        replies=["收到", "等老师版本"],
        note="上下文是班级备考，文本反对传播来路不明材料。",
        counter=["明确等待老师发布。", "没有售卖答案或作弊招揽。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="exam_contextual",
        code="EXAM_CTX",
        variant="paid_answer_hint",
        platform="微信群",
        text="真题不在群里放，想稳的私我，考前最后一批",
        title="考试资料群",
        topic="考试/诈骗边界",
        risk="medium",
        primary="E1_平台黑话",
        note="上下文是考试资料群，私我、想稳、最后一批带有违规交易或诈骗风险。",
        encoding="用真题和想稳包装私下资料交易。",
        support=["要求私下联系。", "考前最后一批制造紧迫感。"],
        counter=["未明确说答案或收费，仍需复核。"],
        replies=["多少钱", "保真吗"],
    ),
    hn(
        axis="meme_forensics",
        cluster="game_term_hard_negative",
        code="GAME_HN",
        variant="normal_game_callout",
        platform="B站",
        text="这个 boss 二阶段会狂暴，奶妈留技能就行",
        title="游戏副本攻略",
        topic="游戏术语边界",
        replies=["机制讲得清楚", "开荒有用"],
        note="上下文是游戏攻略，狂暴和奶妈是游戏术语。",
        counter=["术语含义在游戏语境中明确。", "没有现实暴力或群体攻击指向。"],
    ),
    risky(
        axis="meme_forensics",
        cluster="game_term_contextual",
        code="GAME_CTX",
        variant="game_term_mapping",
        platform="微博",
        text="这波又开二阶段了，下面小怪都开始排队表忠心",
        title="现实组织人事变动讨论",
        topic="游戏术语边界",
        risk="medium",
        primary="C4_典故/物品/符号借用",
        secondary=["D1_反讽"],
        note="上下文是现实组织人事变动，游戏术语被用于现实类比。",
        encoding="用 boss 二阶段和小怪借代现实组织层级。",
        support=["标题为现实组织人事变动。", "表忠心强化现实政治/组织语境。"],
        counter=["目标对象不具体，仍需人工判断。"],
        replies=["别用游戏词了", "太形象"],
    ),
    hn(
        axis="risk_word_context",
        cluster="livestream_hard_negative",
        code="LIVE_HN",
        variant="normal_live_notice",
        platform="抖音",
        text="今晚八点直播讲护肤，不卖课，产品清单会放橱窗",
        title="护肤博主预告",
        topic="直播导流边界",
        replies=["蹲清单", "橱窗能比价"],
        note="上下文是正常直播预告和平台内橱窗。",
        counter=["明确不卖课。", "交易在平台公开橱窗内完成。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="livestream_contextual",
        code="LIVE_CTX",
        variant="offplatform_deal",
        platform="抖音",
        text="直播间别拍，想要优惠的去暗号群，那里不走平台",
        title="带货直播评论区",
        topic="直播导流边界",
        risk="medium",
        primary="E1_平台黑话",
        note="上下文是带货直播，文本引导不走平台的暗号群。",
        encoding="通过暗号群和不走平台规避平台交易流程。",
        support=["明确不走平台。", "要求去暗号群。"],
        counter=["商品类型不明，主要是交易规避风险。"],
        replies=["这样安全吗", "别被骗"],
    ),
    hn(
        axis="risk_word_context",
        cluster="petition_hard_negative",
        code="PETITION_HN",
        variant="property_rights",
        platform="小红书",
        text="业主维权先走物业和街道流程，材料留痕比吵架有用",
        title="小区物业问题讨论",
        topic="维权/动员边界",
        replies=["先收集证据", "别冲动"],
        note="上下文是正规维权流程建议。",
        counter=["建议走正式渠道。", "没有煽动线下冲突。"],
    ),
    risky(
        axis="risk_word_context",
        cluster="petition_contextual",
        code="PETITION_CTX",
        variant="offline_mobilization",
        platform="微信群",
        text="流程没用，今晚都到门口站着，谁不来以后别说话",
        title="小区纠纷群聊",
        topic="维权/动员边界",
        risk="medium",
        primary="E3_话题/热点触发",
        secondary=["D2_夸张/反话"],
        note="上下文是小区纠纷群聊，文本具有线下聚集和施压意味。",
        encoding="用到门口站着表达线下集结。",
        support=["出现今晚、都到门口等行动线索。", "谁不来以后别说话带有群体施压。"],
        counter=["未明确暴力行为，风险低于直接煽动。"],
        replies=["冷静点", "先找街道"],
    ),
    hn(
        axis="risk_word_context",
        cluster="delivery_hard_negative",
        code="DELIVERY_HN",
        variant="normal_errand",
        platform="小红书",
        text="跑腿小哥帮我送文件，全程平台下单，别私下转钱",
        title="同城跑腿体验",
        topic="同城服务边界",
        replies=["平台有保障", "别脱离平台"],
        note="上下文是正常同城跑腿服务，强调平台下单。",
        counter=["明确不私下转钱。", "服务内容是送文件。"],
    ),
]


def write_jsonl(rows: list[dict[str, Any]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")


def main() -> int:
    cases = CASES + ADDITIONAL_CASES
    rows = [build_sample(index, case) for index, case in enumerate(cases, start=1)]
    write_jsonl(rows, OUTPUT_PATH)
    print(f"Wrote {len(rows)} phase-2 seed candidates to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
